#obj-y		+= nfd/

#obj-$(CONFIG_SUN4I_NANDFLASH_TEST)		+= nfd/
#obj-$(CONFIG_SUN4I_NANDFLASH_TEST)		+= nandtest/

obj-$(CONFIG_SUN4I_NANDFLASH_TEST)  += nand.o
nand-y := nfd/nand_blk.o nfd/nand_osal_for_linux.o\
libnand\
nandtest/nand_test.o
