obj-y += axp-mfd.o

#AW1636
#Make this built-in, so that it will be loaded before I2C driver

obj-$(CONFIG_AW1636) += aw1636-board.o
obj-$(CONFIG_AW1636) += aw1636-regu.o
obj-$(CONFIG_AW1636_COU) += aw1636-sply-cou.o
obj-$(CONFIG_AW1636) += virtual1636.o
obj-$(CONFIG_AW1636) += virtual1636_dev.o