#
# Makefile for the aw_gpio .
#

# GPIO CORE
obj-$(CONFIG_NEW_GPIO)          += gpio_aw_core.o
obj-$(CONFIG_GPIO_AW_CLASS)     += gpio_aw_class.o
# GPIO Platform Drivers
obj-$(CONFIG_GPIO_AW)           += gpio_aw.o

